# User and group information
user = "holo"
group = "holo"

# Path to the non-volatile memory storage for configuration transactions,
# graceful-restart information, authentication sequence numbers, and more.
#
# Needs to be writable by @user or @group.
database_path = "/var/opt/holo/holo.db"

# Logging configuration
[logging]
  # Logging to journald
  [logging.journald]
    # Enable or disable
    enabled = false

  # Logging to a file
  [logging.file]
    # Enable or disable
    enabled = true
    # File path (needs to be writable by @user or @group)
    dir = "/var/log/"
    # File name
    name = "holod.log"
    # Log rotation (options: "never", "daily", "hourly")
    rotation = "never"
    # Logging style (options: "full", "compact", "pretty", "json")
    style = "full"
    # Enable or disable ANSI terminal colors
    colors = false
    # Sets whether or not the thread ID of the current thread is displayed
    show_thread_id = false
    # Sets whether or not an event’s source code file path and line number are displayed
    show_source = false

  # Logging to the standard output
  [logging.stdout]
    # Enable or disable
    enabled = false
    # Logging style (options: "full", "compact", "pretty", "json")
    style = "full"
    # Enable or disable ANSI terminal colors
    colors = false
    # Sets whether or not the thread ID of the current thread is displayed
    show_thread_id = false
    # Sets whether or not an event’s source code file path and line number are displayed
    show_source = false

# Event recorder (useful for bug reporting)
[event_recorder]
  # Enable or disable the event recorder
  enabled = false
  # Directory where to save the files (needs to be writable by @user or @group)
  dir = "/var/opt/holo"

# Daemon plugins
[plugins]
  # gRPC northbound plugin configuration
  [plugins.grpc]
    # Enable or disable the plugin
    enabled = true
    # gRPC server listening address
    address = "[::]:50051"
    # Optional gRPC TLS configuration
    [plugins.grpc.tls]
      # Enable or disable TLS authentication
      enabled = false
      # TLS certificate
      certificate = "/etc/ssl/private/holo.pem"
      # TLS key
      key = "/etc/ssl/certs/holo.key"

  # gNMI northbound plugin configuration
  [plugins.gnmi]
    # Enable or disable the plugin
    enabled = true
    # gNMI server listening address
    address = "[::]:10161"
    # Optional gNMI TLS configuration
    [plugins.gnmi.tls]
      # Enable or disable TLS authentication
      enabled = false
      # TLS certificate
      certificate = "/etc/ssl/private/holo.pem"
      # TLS key
      key = "/etc/ssl/certs/holo.key"
